let
    Source = #date(2010, 1, 1),
    Custom1 = List.Dates(Source,Number.From(#date(2012,1,1))-Number.From(Source),#duration(1,0,0,0)),
    #"Convertida en tabla" = Table.FromList(Custom1, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    #"Tipo cambiado" = Table.TransformColumnTypes(#"Convertida en tabla",{{"Column1", type date}}),
    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Tipo cambiado",{{"Column1", "Fechas"}}),
    #"Año insertado" = Table.AddColumn(#"Columnas con nombre cambiado", "Año", each Date.Year([Fechas]), Int64.Type),
    #"Mes insertado" = Table.AddColumn(#"Año insertado", "Mes", each Date.Month([Fechas]), Int64.Type),
    #"Nombre del mes insertado" = Table.AddColumn(#"Mes insertado", "Nombre del mes", each Date.MonthName([Fechas]), type text),
    #"Trimestre insertado" = Table.AddColumn(#"Nombre del mes insertado", "Trimestre", each Date.QuarterOfYear([Fechas]), Int64.Type),
    #"Semana del año insertada" = Table.AddColumn(#"Trimestre insertado", "Semana del año", each Date.WeekOfYear([Fechas]), Int64.Type),
    #"Primeros caracteres extraídos" = Table.TransformColumns(#"Semana del año insertada", {{"Nombre del mes", each Text.Start(_, 3), type text}}),
    #"Filas filtradas" = Table.SelectRows(#"Primeros caracteres extraídos", each [Fechas] <> null and [Fechas] <> ""),
    #"Capitalized Each Word" = Table.TransformColumns(#"Filas filtradas",{{"Nombre del mes", Text.Proper, type text}}),
    #"Inserted Day Name" = Table.AddColumn(#"Capitalized Each Word", "Day Name", each Date.DayOfWeekName([Fechas]), type text),
    #"Inserted Day of Week" = Table.AddColumn(#"Inserted Day Name", "Day of Week", each Date.DayOfWeek([Fechas]), Int64.Type)
in
    #"Inserted Day of Week"
